# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wsn01.ui'
#
# Created: Tue Oct 27 22:33:08 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_WsnViewerUI(object):
    def setupUi(self, WsnViewerUI):
        WsnViewerUI.setObjectName(_fromUtf8("WsnViewerUI"))
        WsnViewerUI.resize(800, 600)
        WsnViewerUI.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Loma"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        WsnViewerUI.setFont(font)
        self.centralwidget = QtGui.QWidget(WsnViewerUI)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.graphicsView = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.verticalLayout_2.addWidget(self.graphicsView)
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.horizontalSlider = QtGui.QSlider(self.widget)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.horizontalLayout.addWidget(self.horizontalSlider)
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.widget)
        WsnViewerUI.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(WsnViewerUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 35))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        WsnViewerUI.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(WsnViewerUI)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        WsnViewerUI.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(WsnViewerUI)
        self.toolBar.setMinimumSize(QtCore.QSize(0, 40))
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        WsnViewerUI.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNew = QtGui.QAction(WsnViewerUI)
        self.actionNew.setEnabled(True)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionOpen = QtGui.QAction(WsnViewerUI)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../WSN01/src/folder-open-empty.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(WsnViewerUI)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("../WsnViewer01/src/save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon1)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionCut = QtGui.QAction(WsnViewerUI)
        self.actionCut.setObjectName(_fromUtf8("actionCut"))
        self.actionCopy = QtGui.QAction(WsnViewerUI)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("../WsnViewer01/src/copy.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopy.setIcon(icon2)
        self.actionCopy.setObjectName(_fromUtf8("actionCopy"))
        self.actionDelete = QtGui.QAction(WsnViewerUI)
        self.actionDelete.setObjectName(_fromUtf8("actionDelete"))
        self.actionFullscreen = QtGui.QAction(WsnViewerUI)
        self.actionFullscreen.setObjectName(_fromUtf8("actionFullscreen"))
        self.actionSide_Panel = QtGui.QAction(WsnViewerUI)
        self.actionSide_Panel.setObjectName(_fromUtf8("actionSide_Panel"))
        self.actionContens = QtGui.QAction(WsnViewerUI)
        self.actionContens.setObjectName(_fromUtf8("actionContens"))
        self.actionAbout = QtGui.QAction(WsnViewerUI)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionRandom_topology = QtGui.QAction(WsnViewerUI)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("../WsnViewer01/src/logoRand.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRandom_topology.setIcon(icon3)
        self.actionRandom_topology.setObjectName(_fromUtf8("actionRandom_topology"))
        self.actionClose = QtGui.QAction(WsnViewerUI)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("../WsnViewer01/src/close.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClose.setIcon(icon4)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionQuit = QtGui.QAction(WsnViewerUI)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("../WsnViewer01/src/quit-512.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon5)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionTools = QtGui.QAction(WsnViewerUI)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("../Icon/tools.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTools.setIcon(icon6)
        self.actionTools.setObjectName(_fromUtf8("actionTools"))
        self.menuFile.addAction(self.actionTools)
        self.menuFile.addAction(self.actionRandom_topology)
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionDelete)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionFullscreen)
        self.menuView.addAction(self.actionSide_Panel)
        self.menuHelp.addAction(self.actionContens)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionCopy)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionTools)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionRandom_topology)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionQuit)

        self.retranslateUi(WsnViewerUI)
        QtCore.QMetaObject.connectSlotsByName(WsnViewerUI)

    def retranslateUi(self, WsnViewerUI):
        WsnViewerUI.setWindowTitle(_translate("WsnViewerUI", "WSN", None))
        self.label.setText(_translate("WsnViewerUI", "All", None))
        self.label_2.setText(_translate("WsnViewerUI", "Strongest", None))
        self.menuFile.setTitle(_translate("WsnViewerUI", "File", None))
        self.menuEdit.setTitle(_translate("WsnViewerUI", "Edit", None))
        self.menuView.setTitle(_translate("WsnViewerUI", "View", None))
        self.menuHelp.setTitle(_translate("WsnViewerUI", "Help", None))
        self.toolBar.setWindowTitle(_translate("WsnViewerUI", "toolBar", None))
        self.actionNew.setText(_translate("WsnViewerUI", "New", None))
        self.actionOpen.setText(_translate("WsnViewerUI", "Open", None))
        self.actionSave.setText(_translate("WsnViewerUI", "Save", None))
        self.actionCut.setText(_translate("WsnViewerUI", "Cut", None))
        self.actionCopy.setText(_translate("WsnViewerUI", "Copy", None))
        self.actionDelete.setText(_translate("WsnViewerUI", "Delete", None))
        self.actionFullscreen.setText(_translate("WsnViewerUI", "Fullscreen", None))
        self.actionSide_Panel.setText(_translate("WsnViewerUI", "Side Panel", None))
        self.actionContens.setText(_translate("WsnViewerUI", "Contens", None))
        self.actionAbout.setText(_translate("WsnViewerUI", "About", None))
        self.actionRandom_topology.setText(_translate("WsnViewerUI", "Random topology", None))
        self.actionClose.setText(_translate("WsnViewerUI", "Close", None))
        self.actionQuit.setText(_translate("WsnViewerUI", "Quit", None))
        self.actionTools.setText(_translate("WsnViewerUI", "Tools", None))
        self.actionTools.setToolTip(_translate("WsnViewerUI", "Tools to generate topology", None))

